{{- if .Values.environment }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quorumkeymanager.fullname" . }}-envmap
  labels:
    {{- include "quorumkeymanager.labels" . | nindent 4 }}
  annotations:
    {{- include "quorumkeymanager.annotations" . | nindent 4 }}
data:
{{- range $key,$value := .Values.environment }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}