{{- if .Values.auth.oidc.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quorumkeymanager.fullname" . }}-oidc-pubkey
  labels:
    {{- include "quorumkeymanager.labels" . | nindent 4 }}
  annotations:
    {{- include "quorumkeymanager.annotations" . | nindent 4 }}
type: Opaque
data:
  oidc.pub: {{ .Values.auth.oidc.pubKey }}

{{- end }}
