apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quorumkeymanager.fullname" . }}
  labels:
    {{- include "quorumkeymanager.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "quorumkeymanager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/manifests: {{ include (print $.Template.BasePath "/manifests-secret.yaml") . | sha256sum }}
        {{- if .Values.environment }}
        checksum/configEnv: {{ include (print $.Template.BasePath "/configmap-env.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.environmentSecrets }}
        checksum/secretEnv: {{ include (print $.Template.BasePath "/secret-env.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "quorumkeymanager.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imageCredentials }}
      imagePullSecrets:
        - name: {{ include "quorumkeymanager.imagePullSecretName" . }}
      {{- end }}
      serviceAccountName: {{ include "quorumkeymanager.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      # to avoid "not found" token issue at start
      initContainers:
        {{- if .Values.vaultAgent.enabled }}
        - name: init-token
          securityContext:
            capabilities:
              add:
              - IPC_LOCK
          image: "{{ .Values.vaultAgent.image.repository }}:{{ .Values.vaultAgent.image.tag }}"
          args:
            - "agent"
            - "-config"
            - "/vault/config/init-agent-config.hcl"
          env:
            - name: SKIP_CHOWN
              value: "true"
          {{- if or .Values.environment .Values.environmentSecrets }}
          envFrom:
            {{- if .Values.environment }}
            - configMapRef:
                name: {{ include "quorumkeymanager.fullname" . }}-envmap
                optional: true
            {{- end }}
            {{- if .Values.environmentSecrets }}
            - secretRef:
                name: {{ include "quorumkeymanager.fullname" . }}-secretmap
                optional: true
            {{- end }}
          {{- end }}
          volumeMounts:
            - name: vault-token
              mountPath: /vault/token
            - name: vault-config
              mountPath: /vault/config
            - name: vault-tls
              mountPath: /vault/tls
        {{- end }}
      containers:
        {{- if .Values.vaultAgent.enabled }}
        - name: vault-agent
          securityContext:
            capabilities:
              add:
              - IPC_LOCK
          image: "{{ .Values.vaultAgent.image.repository }}:{{ .Values.vaultAgent.image.tag }}"
          args:
            - "agent"
            - "-config"
            - "/vault/config/agent-config.hcl"
          env:
            - name: SKIP_CHOWN
              value: "true"
          {{- if or .Values.environment .Values.environmentSecrets }}
          envFrom:
            {{- if .Values.environment }}
            - configMapRef:
                name: {{ include "quorumkeymanager.fullname" . }}-envmap
                optional: true
            {{- end }}
            {{- if .Values.environmentSecrets }}
            - secretRef:
                name: {{ include "quorumkeymanager.fullname" . }}-secretmap
                optional: true
            {{- end }}
          {{- end }}
          volumeMounts:
            - name: vault-token
              mountPath: /vault/token
            - name: vault-config
              mountPath: /vault/config
            - name: vault-tls
              mountPath: /vault/tls
        {{- end }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - run
            - --manifest-path
            - /manifests/manifests.yaml
          {{- if or .Values.environment .Values.environmentSecrets }}
          envFrom:
            {{- if .Values.environment }}
            - configMapRef:
                name: {{ include "quorumkeymanager.fullname" . }}-envmap
                optional: true
            {{- end }}
            {{- if .Values.environmentSecrets }}
            - secretRef:
                name: {{ include "quorumkeymanager.fullname" . }}-secretmap
                optional: true
            {{- end }}
          {{- end }}
          ports:
            - name: http-svc
              containerPort: 8080
              protocol: TCP
            - name: http-metrics
              containerPort: 8081
              protocol: TCP
          volumeMounts:
          {{- if .Values.vaultAgent.enabled }}
            - name: vault-token
              mountPath: /vault/token
              readOnly: true
            - name: vault-tls
              mountPath: /vault/tls
              readOnly: true
          {{- end }}
          {{- if .Values.postgresql.tls.enabled }}
            - name: postgres-certs
              mountPath: /postgres/certs
              readOnly: true
          {{- end }}
          {{- if .Values.auth.apikey.enabled }}
            - name: apikey-file
              mountPath: /apikey
              readOnly: true
          {{- end }}
          {{- if .Values.auth.tls.enabled }}
            - name: qkm-certs
              mountPath: /certificates
              readOnly: true
          {{- end }}
          {{- if .Values.auth.oidc.enabled }}
            - name: oidc-certs
              mountPath: /oidc_certs
              readOnly: true
          {{- end }}
            - name: manifests-config
              mountPath: /manifests
            - name: ca-store
              mountPath: /etc/ssl/certs/others.pem
              subPath: others.pem
              readOnly: false
          livenessProbe:
            httpGet:
          {{- if .Values.auth.tls.enabled }}
              scheme: HTTPS
          {{ end }}
              path: /live
              port: http-metrics
          readinessProbe:
            httpGet:
          {{- if .Values.auth.tls.enabled }}
              scheme: HTTPS
          {{ end }}
              path: /ready
              port: http-metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      {{- if .Values.vaultAgent.enabled }}
        - name: vault-token
          emptyDir:
            sizeLimit: 1M
        - name: vault-config
          configMap:
            name: {{ include "quorumkeymanager.fullname" . }}-vault-agent
        - name: vault-tls
          secret:
            secretName: {{ include "quorumkeymanager.fullname" . }}-vault-certs
      {{- end }}
      {{- if .Values.postgresql.tls.enabled }}
        - name: postgres-certs
          secret:
            secretName: {{ include "quorumkeymanager.fullname" . }}-postgres-certs
      {{- end }}
      {{- if .Values.auth.apikey.enabled }}
        - name: apikey-file
          configMap:
            name: {{ include "quorumkeymanager.fullname" . }}-apikey-file
      {{- end }}
      {{- if .Values.auth.tls.enabled }}
        - name: qkm-certs
          secret:
            secretName: {{ .Values.auth.tls.secretName }}
      {{- end }}
      {{- if .Values.auth.oidc.enabled }}
        - name: oidc-certs
          secret:
            secretName: {{ include "quorumkeymanager.fullname" . }}-oidc-certs
      {{- end }}
        - name: manifests-config
          secret:
            secretName: {{ include "quorumkeymanager.fullname" . }}-manifests
        - name: ca-store
          configMap:
            name: {{ include "quorumkeymanager.fullname" . }}-other-certs
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
