apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quorum-key-manager.fullname" . }}
  labels:
    {{- include "quorum-key-manager.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "quorum-key-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "quorum-key-manager.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imageCredentials }}
      imagePullSecrets:
        - name: {{ include "quorum-key-manager.imagePullSecretName" . }}
      {{- end }}
      serviceAccountName: {{ include "quorum-key-manager.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - run
            - --manifest-path 
            - /manifests
          ports:
            - name: http-svc
              containerPort: 8080
              protocol: TCP
            - name: http-metrics
              containerPort: 8081
              protocol: TCP
          volumeMounts:
            - name: manifests-config
              mountPath: /manifests
          livenessProbe:
            httpGet:
              path: /live
              port: http-metrics
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: manifests-config
          configMap:
            name: {{ include "quorum-key-manager.fullname" . }}-manifests

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
