{{- if .Values.migrate.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quorumkeymanager.fullname" . }}-hook-envmap
  annotations:
    {{- include "quorumkeymanager.annotations" . | nindent 4 }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    {{- include "quorumkeymanager.labels" . | nindent 4 }}
data:
{{- range $key,$value := .Values.environment }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- if .Values.environmentSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "quorumkeymanager.fullname" . }}-hook-secretmap
  annotations:
    {{- include "quorumkeymanager.annotations" . | nindent 4 }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    {{- include "quorumkeymanager.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key,$value := .Values.environmentSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "quorumkeymanager.fullname" . }}-migrate-init-job
  labels:
    {{- include "quorumkeymanager.labels" . | nindent 4 }}
  annotations:
    {{- include "quorumkeymanager.annotations" . | nindent 4 }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: {{ .Values.migrate.backoffLimit }}
  template:
    metadata:
      name: migrate-init
      labels:
        {{- include "quorumkeymanager.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- if .Values.imageCredentials }}
      imagePullSecrets:
        - name: {{ include "quorumkeymanager.imagePullSecretName" . }}
      {{- end }}
      containers:
        - name: {{ template "quorumkeymanager.fullname" . }}-initdb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /main
          args:
            - migrate
            - up
          envFrom:
            - configMapRef:
                name: {{ include "quorumkeymanager.fullname" . }}-hook-envmap
            {{- if .Values.environmentSecrets }}
            - secretRef:
                name: {{ include "quorumkeymanager.fullname" . }}-hook-secretmap
                optional: true
            {{- end }}
          volumeMounts:
          {{- if .Values.postgresql.tls.enabled }}
            - name: postgres-certs
              mountPath: /postgres/certs
              readOnly: true
          {{- end }}
      volumes:
      {{- if .Values.postgresql.tls.enabled }}
        - name: postgres-certs
          secret:
            secretName: {{ include "quorumkeymanager.fullname" . }}-postgres-certs
      {{- end }}
            
{{- end }}
