{{- if .Values.storage.nfs.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "quorumkeymanager.fullname" . }}-nfs-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ template "quorumkeymanager.fullname" . }}-nfs-sc
  csi:
    driver: {{ .Values.storage.nfs.driver }}
    volumeHandle: {{ .Values.storage.nfs.fsID }}

{{- end }}