{{- if .Values.imageCredentials.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "quorumkeymanager.imagePullSecretName" . }}
  annotations:
    {{- include "quorumkeymanager.annotations" . | nindent 4 }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "5"
  labels:
    {{- include "quorumkeymanager.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "quorumkeymanager.imagePullSecret" . }}
{{- end }}
