apiVersion: v1
kind: Service
metadata:
  name: {{ include "quorum-key-manager-helm.fullname" . }}
  labels:
    {{- include "quorum-key-manager-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http-svc
      protocol: TCP
      name: http-svc
    - port: {{ .Values.service.metrics.port }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "quorum-key-manager-helm.selectorLabels" . | nindent 4 }}
